insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 1,'Eula Lane','jigrormo','jigrormo','jigrormo','jigrormo','jigrormo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 2,'Barry Rodriquez','zun','zun','zun','zun','zun')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 3,'Eugenia Selvi','capfad','capfad','capfad','capfad','capfad')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 4,'Alejandro Miles','dec','dec','dec','dec','dec')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 5,'Cora Tesi','bivo','bivo','bivo','bivo','bivo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 6,'Marguerite Ishii','judbilo','judbilo','judbilo','judbilo','judbilo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 7,'Mildred Jacobs','joraf','joraf','joraf','joraf','joraf')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 8,'Gene Goodman','kem','kem','kem','kem','kem')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 9,'Lettie Bennett','odeter','odeter','odeter','odeter','odeter')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 10,'Mabel Leach','lisohuje','lisohuje','lisohuje','lisohuje','lisohuje')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 11,'Jordan Miccinesi','duod','duod','duod','duod','duod')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 12,'Marie Parkes','nowufpus','nowufpus','nowufpus','nowufpus','nowufpus')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 13,'Rose Gray','kagu','kagu','kagu','kagu','kagu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 14,'Garrett Stokes','fef','fef','fef','fef','fef')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 15,'Barbara Matthieu','derwogi','derwogi','derwogi','derwogi','derwogi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 16,'Jean Rhodes','wehovuce','wehovuce','wehovuce','wehovuce','wehovuce')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 17,'Jack Romoli','zamum','zamum','zamum','zamum','zamum')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 18,'Pearl Holden','dunebuh','dunebuh','dunebuh','dunebuh','dunebuh')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 19,'Belle Montero','repiwid','repiwid','repiwid','repiwid','repiwid')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 20,'Olive Molina','razuppa','razuppa','razuppa','razuppa','razuppa')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 21,'Minerva Todd','kulmenim','kulmenim','kulmenim','kulmenim','kulmenim')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 22,'Bobby Pearson','ib','ib','ib','ib','ib')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 23,'Larry Ciappi','ba','ba','ba','ba','ba')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 24,'Ronnie Salucci','tohhij','tohhij','tohhij','tohhij','tohhij')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 25,'Walter Grossi','tuvo','tuvo','tuvo','tuvo','tuvo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 26,'Frances Koopmans','foga','foga','foga','foga','foga')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 27,'Frances Fujimoto','uswuzzub','uswuzzub','uswuzzub','uswuzzub','uswuzzub')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 28,'Olivia Vidal','hivwerip','hivwerip','hivwerip','hivwerip','hivwerip')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 29,'Edna Henry','gugusu','gugusu','gugusu','gugusu','gugusu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 30,'Lydia Brun','zedekak','zedekak','zedekak','zedekak','zedekak')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 31,'Jay Blake','ral','ral','ral','ral','ral')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 32,'Isabel Serafini','turuhu','turuhu','turuhu','turuhu','turuhu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 33,'Rebecca Carter','omjo','omjo','omjo','omjo','omjo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 34,'Maurice Fabbrini','rig','rig','rig','rig','rig')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 35,'Ollie Turnbull','sicewap','sicewap','sicewap','sicewap','sicewap')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 36,'Jerry Hopkins','fo','fo','fo','fo','fo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 37,'Nora Lyons','gegijap','gegijap','gegijap','gegijap','gegijap')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 38,'Anne Weiß','kuvesa','kuvesa','kuvesa','kuvesa','kuvesa')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 39,'Louise Gauthier','lapahu','lapahu','lapahu','lapahu','lapahu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 40,'Lloyd Fani','zev','zev','zev','zev','zev')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 41,'Maud Dunn','nabeaga','nabeaga','nabeaga','nabeaga','nabeaga')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 42,'Henry Gigli','kaot','kaot','kaot','kaot','kaot')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 43,'Virgie Werner','tawuctuj','tawuctuj','tawuctuj','tawuctuj','tawuctuj')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 44,'Gregory Cozzi','eh','eh','eh','eh','eh')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 45,'Lucinda Gil','fajjusuz','fajjusuz','fajjusuz','fajjusuz','fajjusuz')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 46,'Gertrude Verbeek','pave','pave','pave','pave','pave')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 47,'Mattie Graham','ispaviw','ispaviw','ispaviw','ispaviw','ispaviw')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 48,'Bryan Shaw','ha','ha','ha','ha','ha')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 49,'Essie Adams','iliat','iliat','iliat','iliat','iliat')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 50,'Gary Osborne','do','do','do','do','do')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 51,'Richard Silva','wi','wi','wi','wi','wi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 52,'Dustin Pestelli','iwage','iwage','iwage','iwage','iwage')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 53,'Henrietta Hilton','joopoju','joopoju','joopoju','joopoju','joopoju')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 54,'Francisco Giordano','gojawu','gojawu','gojawu','gojawu','gojawu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 55,'Cynthia Sardi','afigoh','afigoh','afigoh','afigoh','afigoh')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 56,'Lula Testi','benom','benom','benom','benom','benom')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 57,'Bess Lucas','jevakbe','jevakbe','jevakbe','jevakbe','jevakbe')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 58,'Linnie Driessen','darhow','darhow','darhow','darhow','darhow')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 59,'Eva Tesi','dupid','dupid','dupid','dupid','dupid')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 60,'Augusta Sakai','comouc','comouc','comouc','comouc','comouc')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 61,'Mathilda Schwarz','igunisi','igunisi','igunisi','igunisi','igunisi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 62,'Joe Riley','pe','pe','pe','pe','pe')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 63,'Leon McGee','puk','puk','puk','puk','puk')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 64,'Florence Viviani','vegub','vegub','vegub','vegub','vegub')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 65,'Lee Miceli','rucwi','rucwi','rucwi','rucwi','rucwi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 66,'Celia Sodi','agijit','agijit','agijit','agijit','agijit')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 67,'Aaron Misuri','loolu','loolu','loolu','loolu','loolu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 68,'Fanny Parkinson','tupwovali','tupwovali','tupwovali','tupwovali','tupwovali')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 69,'Phoebe Vitale','hidge','hidge','hidge','hidge','hidge')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 70,'Edith Brennan','liowci','liowci','liowci','liowci','liowci')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 71,'Jeremy Marilli','vesa','vesa','vesa','vesa','vesa')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 72,'Kathryn Huet','wupikdoh','wupikdoh','wupikdoh','wupikdoh','wupikdoh')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 73,'Lelia Matsuo','dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 74,'Virginia Woods','soofpe','soofpe','soofpe','soofpe','soofpe')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 75,'Sally Aoki','aruzusjas','aruzusjas','aruzusjas','aruzusjas','aruzusjas')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 76,'Isabelle de Ridder','ufeco','ufeco','ufeco','ufeco','ufeco')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 77,'Rosie Murphy','uneehi','uneehi','uneehi','uneehi','uneehi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 78,'Lou Meyer','hahinaba','hahinaba','hahinaba','hahinaba','hahinaba')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 79,'Rodney Love','zun','zun','zun','zun','zun')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 80,'Kenneth Bianchini','jo','jo','jo','jo','jo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 81,'Essie Dietrich','goltuefo','goltuefo','goltuefo','goltuefo','goltuefo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 82,'Leila Simon','lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 83,'Eva Pierre','reduzris','reduzris','reduzris','reduzris','reduzris')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 84,'Landon Moretti','pubsav','pubsav','pubsav','pubsav','pubsav')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 85,'Mittie Sardi','lullip','lullip','lullip','lullip','lullip')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 86,'Corey McDaniel','aba','aba','aba','aba','aba')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 87,'Hester Stein','kettujwo','kettujwo','kettujwo','kettujwo','kettujwo')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 88,'Danny Lowe','ju','ju','ju','ju','ju')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 89,'Lillie Winter','vioburez','vioburez','vioburez','vioburez','vioburez')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 90,'Brandon Borchi','ig','ig','ig','ig','ig')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 91,'Isaac Bernardi','omu','omu','omu','omu','omu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 92,'Clyde Crawford','luw','luw','luw','luw','luw')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 93,'Paul Sherman','pi','pi','pi','pi','pi')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 94,'Craig Russell','zu','zu','zu','zu','zu')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 95,'John Sutton','ag','ag','ag','ag','ag')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 96,'Francisco Formigli','fopav','fopav','fopav','fopav','fopav')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 97,'Gary Baker','ji','ji','ji','ji','ji')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 98,'Earl Giovannoni','lojet','lojet','lojet','lojet','lojet')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 99,'Helen Zanieri','ukve','ukve','ukve','ukve','ukve')
insert into superhero(version, id,name,spname,occupation,home_city,universe,first_apperiance) values (1, 100,'Agnes Toccafondi','viipo','viipo','viipo','viipo','viipo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 1,'jigrormo','jigrormo','jigrormo','jigrormo','jigrormo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 2,'zun','zun','zun','zun','zun')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 3,'capfad','capfad','capfad','capfad','capfad')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 4,'dec','dec','dec','dec','dec')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 5,'bivo','bivo','bivo','bivo','bivo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 6,'judbilo','judbilo','judbilo','judbilo','judbilo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 7,'joraf','joraf','joraf','joraf','joraf')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 8,'kem','kem','kem','kem','kem')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 9,'odeter','odeter','odeter','odeter','odeter')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 10,'lisohuje','lisohuje','lisohuje','lisohuje','lisohuje')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 11,'duod','duod','duod','duod','duod')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 12,'nowufpus','nowufpus','nowufpus','nowufpus','nowufpus')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 13,'kagu','kagu','kagu','kagu','kagu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 14,'fef','fef','fef','fef','fef')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 15,'derwogi','derwogi','derwogi','derwogi','derwogi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 16,'wehovuce','wehovuce','wehovuce','wehovuce','wehovuce')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 17,'zamum','zamum','zamum','zamum','zamum')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 18,'dunebuh','dunebuh','dunebuh','dunebuh','dunebuh')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 19,'repiwid','repiwid','repiwid','repiwid','repiwid')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 20,'razuppa','razuppa','razuppa','razuppa','razuppa')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 21,'kulmenim','kulmenim','kulmenim','kulmenim','kulmenim')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 22,'ib','ib','ib','ib','ib')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 23,'ba','ba','ba','ba','ba')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 24,'tohhij','tohhij','tohhij','tohhij','tohhij')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 25,'tuvo','tuvo','tuvo','tuvo','tuvo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 26,'foga','foga','foga','foga','foga')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 27,'uswuzzub','uswuzzub','uswuzzub','uswuzzub','uswuzzub')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 28,'hivwerip','hivwerip','hivwerip','hivwerip','hivwerip')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 29,'gugusu','gugusu','gugusu','gugusu','gugusu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 30,'zedekak','zedekak','zedekak','zedekak','zedekak')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 31,'ral','ral','ral','ral','ral')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 32,'turuhu','turuhu','turuhu','turuhu','turuhu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 33,'omjo','omjo','omjo','omjo','omjo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 34,'rig','rig','rig','rig','rig')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 35,'sicewap','sicewap','sicewap','sicewap','sicewap')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 36,'fo','fo','fo','fo','fo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 37,'gegijap','gegijap','gegijap','gegijap','gegijap')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 38,'kuvesa','kuvesa','kuvesa','kuvesa','kuvesa')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 39,'lapahu','lapahu','lapahu','lapahu','lapahu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 40,'zev','zev','zev','zev','zev')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 41,'nabeaga','nabeaga','nabeaga','nabeaga','nabeaga')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 42,'kaot','kaot','kaot','kaot','kaot')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 43,'tawuctuj','tawuctuj','tawuctuj','tawuctuj','tawuctuj')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 44,'eh','eh','eh','eh','eh')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 45,'fajjusuz','fajjusuz','fajjusuz','fajjusuz','fajjusuz')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 46,'pave','pave','pave','pave','pave')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 47,'ispaviw','ispaviw','ispaviw','ispaviw','ispaviw')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 48,'ha','ha','ha','ha','ha')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 49,'iliat','iliat','iliat','iliat','iliat')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 50,'do','do','do','do','do')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 51,'wi','wi','wi','wi','wi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 52,'iwage','iwage','iwage','iwage','iwage')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 53,'joopoju','joopoju','joopoju','joopoju','joopoju')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 54,'gojawu','gojawu','gojawu','gojawu','gojawu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 55,'afigoh','afigoh','afigoh','afigoh','afigoh')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 56,'benom','benom','benom','benom','benom')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 57,'jevakbe','jevakbe','jevakbe','jevakbe','jevakbe')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 58,'darhow','darhow','darhow','darhow','darhow')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 59,'dupid','dupid','dupid','dupid','dupid')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 60,'comouc','comouc','comouc','comouc','comouc')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 61,'igunisi','igunisi','igunisi','igunisi','igunisi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 62,'pe','pe','pe','pe','pe')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 63,'puk','puk','puk','puk','puk')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 64,'vegub','vegub','vegub','vegub','vegub')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 65,'rucwi','rucwi','rucwi','rucwi','rucwi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 66,'agijit','agijit','agijit','agijit','agijit')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 67,'loolu','loolu','loolu','loolu','loolu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 68,'tupwovali','tupwovali','tupwovali','tupwovali','tupwovali')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 69,'hidge','hidge','hidge','hidge','hidge')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 70,'liowci','liowci','liowci','liowci','liowci')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 71,'vesa','vesa','vesa','vesa','vesa')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 72,'wupikdoh','wupikdoh','wupikdoh','wupikdoh','wupikdoh')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 73,'dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 74,'soofpe','soofpe','soofpe','soofpe','soofpe')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 75,'aruzusjas','aruzusjas','aruzusjas','aruzusjas','aruzusjas')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 76,'ufeco','ufeco','ufeco','ufeco','ufeco')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 77,'uneehi','uneehi','uneehi','uneehi','uneehi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 78,'hahinaba','hahinaba','hahinaba','hahinaba','hahinaba')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 79,'zun','zun','zun','zun','zun')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 80,'jo','jo','jo','jo','jo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 81,'goltuefo','goltuefo','goltuefo','goltuefo','goltuefo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 82,'lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 83,'reduzris','reduzris','reduzris','reduzris','reduzris')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 84,'pubsav','pubsav','pubsav','pubsav','pubsav')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 85,'lullip','lullip','lullip','lullip','lullip')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 86,'aba','aba','aba','aba','aba')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 87,'kettujwo','kettujwo','kettujwo','kettujwo','kettujwo')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 88,'ju','ju','ju','ju','ju')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 89,'vioburez','vioburez','vioburez','vioburez','vioburez')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 90,'ig','ig','ig','ig','ig')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 91,'omu','omu','omu','omu','omu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 92,'luw','luw','luw','luw','luw')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 93,'pi','pi','pi','pi','pi')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 94,'zu','zu','zu','zu','zu')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 95,'ag','ag','ag','ag','ag')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 96,'fopav','fopav','fopav','fopav','fopav')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 97,'ji','ji','ji','ji','ji')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 98,'lojet','lojet','lojet','lojet','lojet')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 99,'ukve','ukve','ukve','ukve','ukve')
insert into powers(version, id,power_name,description,type,strenght_lvl,is_rare) values (1, 100,'viipo','viipo','viipo','viipo','viipo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 1,'jigrormo','jigrormo','jigrormo','jigrormo','jigrormo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 2,'zun','zun','zun','zun','zun')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 3,'capfad','capfad','capfad','capfad','capfad')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 4,'dec','dec','dec','dec','dec')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 5,'bivo','bivo','bivo','bivo','bivo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 6,'judbilo','judbilo','judbilo','judbilo','judbilo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 7,'joraf','joraf','joraf','joraf','joraf')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 8,'kem','kem','kem','kem','kem')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 9,'odeter','odeter','odeter','odeter','odeter')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 10,'lisohuje','lisohuje','lisohuje','lisohuje','lisohuje')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 11,'duod','duod','duod','duod','duod')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 12,'nowufpus','nowufpus','nowufpus','nowufpus','nowufpus')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 13,'kagu','kagu','kagu','kagu','kagu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 14,'fef','fef','fef','fef','fef')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 15,'derwogi','derwogi','derwogi','derwogi','derwogi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 16,'wehovuce','wehovuce','wehovuce','wehovuce','wehovuce')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 17,'zamum','zamum','zamum','zamum','zamum')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 18,'dunebuh','dunebuh','dunebuh','dunebuh','dunebuh')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 19,'repiwid','repiwid','repiwid','repiwid','repiwid')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 20,'razuppa','razuppa','razuppa','razuppa','razuppa')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 21,'kulmenim','kulmenim','kulmenim','kulmenim','kulmenim')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 22,'ib','ib','ib','ib','ib')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 23,'ba','ba','ba','ba','ba')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 24,'tohhij','tohhij','tohhij','tohhij','tohhij')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 25,'tuvo','tuvo','tuvo','tuvo','tuvo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 26,'foga','foga','foga','foga','foga')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 27,'uswuzzub','uswuzzub','uswuzzub','uswuzzub','uswuzzub')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 28,'hivwerip','hivwerip','hivwerip','hivwerip','hivwerip')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 29,'gugusu','gugusu','gugusu','gugusu','gugusu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 30,'zedekak','zedekak','zedekak','zedekak','zedekak')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 31,'ral','ral','ral','ral','ral')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 32,'turuhu','turuhu','turuhu','turuhu','turuhu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 33,'omjo','omjo','omjo','omjo','omjo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 34,'rig','rig','rig','rig','rig')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 35,'sicewap','sicewap','sicewap','sicewap','sicewap')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 36,'fo','fo','fo','fo','fo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 37,'gegijap','gegijap','gegijap','gegijap','gegijap')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 38,'kuvesa','kuvesa','kuvesa','kuvesa','kuvesa')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 39,'lapahu','lapahu','lapahu','lapahu','lapahu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 40,'zev','zev','zev','zev','zev')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 41,'nabeaga','nabeaga','nabeaga','nabeaga','nabeaga')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 42,'kaot','kaot','kaot','kaot','kaot')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 43,'tawuctuj','tawuctuj','tawuctuj','tawuctuj','tawuctuj')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 44,'eh','eh','eh','eh','eh')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 45,'fajjusuz','fajjusuz','fajjusuz','fajjusuz','fajjusuz')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 46,'pave','pave','pave','pave','pave')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 47,'ispaviw','ispaviw','ispaviw','ispaviw','ispaviw')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 48,'ha','ha','ha','ha','ha')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 49,'iliat','iliat','iliat','iliat','iliat')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 50,'do','do','do','do','do')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 51,'wi','wi','wi','wi','wi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 52,'iwage','iwage','iwage','iwage','iwage')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 53,'joopoju','joopoju','joopoju','joopoju','joopoju')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 54,'gojawu','gojawu','gojawu','gojawu','gojawu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 55,'afigoh','afigoh','afigoh','afigoh','afigoh')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 56,'benom','benom','benom','benom','benom')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 57,'jevakbe','jevakbe','jevakbe','jevakbe','jevakbe')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 58,'darhow','darhow','darhow','darhow','darhow')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 59,'dupid','dupid','dupid','dupid','dupid')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 60,'comouc','comouc','comouc','comouc','comouc')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 61,'igunisi','igunisi','igunisi','igunisi','igunisi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 62,'pe','pe','pe','pe','pe')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 63,'puk','puk','puk','puk','puk')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 64,'vegub','vegub','vegub','vegub','vegub')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 65,'rucwi','rucwi','rucwi','rucwi','rucwi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 66,'agijit','agijit','agijit','agijit','agijit')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 67,'loolu','loolu','loolu','loolu','loolu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 68,'tupwovali','tupwovali','tupwovali','tupwovali','tupwovali')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 69,'hidge','hidge','hidge','hidge','hidge')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 70,'liowci','liowci','liowci','liowci','liowci')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 71,'vesa','vesa','vesa','vesa','vesa')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 72,'wupikdoh','wupikdoh','wupikdoh','wupikdoh','wupikdoh')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 73,'dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 74,'soofpe','soofpe','soofpe','soofpe','soofpe')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 75,'aruzusjas','aruzusjas','aruzusjas','aruzusjas','aruzusjas')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 76,'ufeco','ufeco','ufeco','ufeco','ufeco')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 77,'uneehi','uneehi','uneehi','uneehi','uneehi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 78,'hahinaba','hahinaba','hahinaba','hahinaba','hahinaba')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 79,'zun','zun','zun','zun','zun')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 80,'jo','jo','jo','jo','jo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 81,'goltuefo','goltuefo','goltuefo','goltuefo','goltuefo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 82,'lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 83,'reduzris','reduzris','reduzris','reduzris','reduzris')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 84,'pubsav','pubsav','pubsav','pubsav','pubsav')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 85,'lullip','lullip','lullip','lullip','lullip')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 86,'aba','aba','aba','aba','aba')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 87,'kettujwo','kettujwo','kettujwo','kettujwo','kettujwo')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 88,'ju','ju','ju','ju','ju')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 89,'vioburez','vioburez','vioburez','vioburez','vioburez')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 90,'ig','ig','ig','ig','ig')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 91,'omu','omu','omu','omu','omu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 92,'luw','luw','luw','luw','luw')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 93,'pi','pi','pi','pi','pi')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 94,'zu','zu','zu','zu','zu')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 95,'ag','ag','ag','ag','ag')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 96,'fopav','fopav','fopav','fopav','fopav')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 97,'ji','ji','ji','ji','ji')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 98,'lojet','lojet','lojet','lojet','lojet')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 99,'ukve','ukve','ukve','ukve','ukve')
insert into publishers(version, id,publisher_name,country,founded_year,ceo,universe) values (1, 100,'viipo','viipo','viipo','viipo','viipo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 1,'jigrormo','jigrormo','jigrormo','jigrormo','jigrormo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 2,'zun','zun','zun','zun','zun')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 3,'capfad','capfad','capfad','capfad','capfad')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 4,'dec','dec','dec','dec','dec')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 5,'bivo','bivo','bivo','bivo','bivo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 6,'judbilo','judbilo','judbilo','judbilo','judbilo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 7,'joraf','joraf','joraf','joraf','joraf')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 8,'kem','kem','kem','kem','kem')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 9,'odeter','odeter','odeter','odeter','odeter')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 10,'lisohuje','lisohuje','lisohuje','lisohuje','lisohuje')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 11,'duod','duod','duod','duod','duod')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 12,'nowufpus','nowufpus','nowufpus','nowufpus','nowufpus')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 13,'kagu','kagu','kagu','kagu','kagu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 14,'fef','fef','fef','fef','fef')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 15,'derwogi','derwogi','derwogi','derwogi','derwogi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 16,'wehovuce','wehovuce','wehovuce','wehovuce','wehovuce')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 17,'zamum','zamum','zamum','zamum','zamum')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 18,'dunebuh','dunebuh','dunebuh','dunebuh','dunebuh')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 19,'repiwid','repiwid','repiwid','repiwid','repiwid')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 20,'razuppa','razuppa','razuppa','razuppa','razuppa')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 21,'kulmenim','kulmenim','kulmenim','kulmenim','kulmenim')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 22,'ib','ib','ib','ib','ib')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 23,'ba','ba','ba','ba','ba')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 24,'tohhij','tohhij','tohhij','tohhij','tohhij')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 25,'tuvo','tuvo','tuvo','tuvo','tuvo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 26,'foga','foga','foga','foga','foga')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 27,'uswuzzub','uswuzzub','uswuzzub','uswuzzub','uswuzzub')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 28,'hivwerip','hivwerip','hivwerip','hivwerip','hivwerip')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 29,'gugusu','gugusu','gugusu','gugusu','gugusu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 30,'zedekak','zedekak','zedekak','zedekak','zedekak')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 31,'ral','ral','ral','ral','ral')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 32,'turuhu','turuhu','turuhu','turuhu','turuhu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 33,'omjo','omjo','omjo','omjo','omjo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 34,'rig','rig','rig','rig','rig')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 35,'sicewap','sicewap','sicewap','sicewap','sicewap')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 36,'fo','fo','fo','fo','fo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 37,'gegijap','gegijap','gegijap','gegijap','gegijap')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 38,'kuvesa','kuvesa','kuvesa','kuvesa','kuvesa')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 39,'lapahu','lapahu','lapahu','lapahu','lapahu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 40,'zev','zev','zev','zev','zev')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 41,'nabeaga','nabeaga','nabeaga','nabeaga','nabeaga')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 42,'kaot','kaot','kaot','kaot','kaot')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 43,'tawuctuj','tawuctuj','tawuctuj','tawuctuj','tawuctuj')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 44,'eh','eh','eh','eh','eh')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 45,'fajjusuz','fajjusuz','fajjusuz','fajjusuz','fajjusuz')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 46,'pave','pave','pave','pave','pave')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 47,'ispaviw','ispaviw','ispaviw','ispaviw','ispaviw')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 48,'ha','ha','ha','ha','ha')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 49,'iliat','iliat','iliat','iliat','iliat')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 50,'do','do','do','do','do')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 51,'wi','wi','wi','wi','wi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 52,'iwage','iwage','iwage','iwage','iwage')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 53,'joopoju','joopoju','joopoju','joopoju','joopoju')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 54,'gojawu','gojawu','gojawu','gojawu','gojawu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 55,'afigoh','afigoh','afigoh','afigoh','afigoh')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 56,'benom','benom','benom','benom','benom')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 57,'jevakbe','jevakbe','jevakbe','jevakbe','jevakbe')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 58,'darhow','darhow','darhow','darhow','darhow')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 59,'dupid','dupid','dupid','dupid','dupid')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 60,'comouc','comouc','comouc','comouc','comouc')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 61,'igunisi','igunisi','igunisi','igunisi','igunisi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 62,'pe','pe','pe','pe','pe')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 63,'puk','puk','puk','puk','puk')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 64,'vegub','vegub','vegub','vegub','vegub')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 65,'rucwi','rucwi','rucwi','rucwi','rucwi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 66,'agijit','agijit','agijit','agijit','agijit')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 67,'loolu','loolu','loolu','loolu','loolu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 68,'tupwovali','tupwovali','tupwovali','tupwovali','tupwovali')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 69,'hidge','hidge','hidge','hidge','hidge')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 70,'liowci','liowci','liowci','liowci','liowci')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 71,'vesa','vesa','vesa','vesa','vesa')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 72,'wupikdoh','wupikdoh','wupikdoh','wupikdoh','wupikdoh')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 73,'dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj','dajsiphaj')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 74,'soofpe','soofpe','soofpe','soofpe','soofpe')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 75,'aruzusjas','aruzusjas','aruzusjas','aruzusjas','aruzusjas')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 76,'ufeco','ufeco','ufeco','ufeco','ufeco')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 77,'uneehi','uneehi','uneehi','uneehi','uneehi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 78,'hahinaba','hahinaba','hahinaba','hahinaba','hahinaba')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 79,'zun','zun','zun','zun','zun')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 80,'jo','jo','jo','jo','jo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 81,'goltuefo','goltuefo','goltuefo','goltuefo','goltuefo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 82,'lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo','lupuwuzo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 83,'reduzris','reduzris','reduzris','reduzris','reduzris')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 84,'pubsav','pubsav','pubsav','pubsav','pubsav')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 85,'lullip','lullip','lullip','lullip','lullip')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 86,'aba','aba','aba','aba','aba')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 87,'kettujwo','kettujwo','kettujwo','kettujwo','kettujwo')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 88,'ju','ju','ju','ju','ju')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 89,'vioburez','vioburez','vioburez','vioburez','vioburez')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 90,'ig','ig','ig','ig','ig')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 91,'omu','omu','omu','omu','omu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 92,'luw','luw','luw','luw','luw')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 93,'pi','pi','pi','pi','pi')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 94,'zu','zu','zu','zu','zu')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 95,'ag','ag','ag','ag','ag')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 96,'fopav','fopav','fopav','fopav','fopav')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 97,'ji','ji','ji','ji','ji')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 98,'lojet','lojet','lojet','lojet','lojet')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 99,'ukve','ukve','ukve','ukve','ukve')
insert into hero_profile(version, id,weakness,threat_lvl,mentor,secret_base,first_mission) values (1, 100,'viipo','viipo','viipo','viipo','viipo')
